# Servlet Container & Health Setup
server:
  address: 0.0.0.0
management:
  endpoints:
    web.exposure.include: info,health,camelroutes
  endpoint:
    health:
      enabled: true
    camelroutes:
      enabled: true
      read-only: true

# Spring Boot
spring:
  artemis:
    mode: NATIVE
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

# IBM MQ
ibm:
  mq:
    queue-manager: QM1
    channel: DEV.APP.SVRCONN
    conn-name: localhost(1414)
    user: app
    password: passw0rd

# Camel Spring Boot
camel:
  springboot:
    name: camel-jms-bridge
    main-run-controller: true

# Logging
logging:
  level:
    #root: ERROR
    com.redhat.examples: DEBUG
